try:
  fopen = open(\8\errors.py, 'r')
  content = fopen.read()
finally:
  fopen.close()